### ISSUE TITLE
Add XL7219

### ISSUE THREAD

**Issue by neilenns** [MobiFlight/kicad-sim-panel-components#20]
Datasheet: Download from https://jlcpcb.com/partdetail/Xinluda-XL7219/C561315 (no direct link available)
Footprint: I think it's SOP-24-7.5x15.4mm_P1.27mm

**Comment by neilenns** [comment]
Yes, this is a drop in replacement for the MAX7219 but this gives us a way to link the datasheet, footprint, and update one of the pin names to match the data sheet's naming :D

**Comment by neilenns** [comment]
The pin rename isn't necessary since the chip specifically uses LOAD not CS. Will update.

**Comment by tigert** [comment]
Hey Neil, do you plan to resurrect this? I mean its the same as MAX7219 essentially but if it comes with the part number for jlc, not the worst idea. Have you tested this chip btw if it works ok?

**Comment by neilenns** [comment]
I'd forgotten this was assigned to me. No, no plans to do this :)

**Comment by tigert** [comment]
ok closing, thx
